name: Lint, Convert, and Commit

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint_and_convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier to format code
        run: npx prettier --write '**/*.{js,json,css,html}'

      - name: Run convert.js script
        run: node convert.js

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add and commit all changes if any
        run: |
          git add .  # Add all modified files
          if git diff --cached --exit-code; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generated commit with changes"
          fi

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
